name: CI

on: push

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node }} in ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
